version: '3.8'

services:
  ltdlg-database: 
    container_name: ltdlg-database 
    build: .
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT} 
    
  ltdlg-pg-admin: 
    container_name: ltdlg-pg-admin
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGAMIN_LISTEN_PORT: ${PGA_PORT} 
    ports: 
      - ${PGA_PORT}:${CONTAINER_PORT}
    depends_on:
      - ltdlg-database